version: "3.7"
services:
  students:
    image: students-jib:0.2.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on: [ postgres ]
    environment:
      DB_HOSTNAME: postgres
#      DB_PORT: 5432
#      DB_NAME: students
#      DB_USERNAME: studentapp
#      DB_PASSWORD: jakosiguranpass
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_USER: studentapp
      POSTGRES_PASSWORD: jakosiguranpass
      POSTGRES_DB: students
volumes:
  db-data:
 
